version: "3"
services:
    broker:
        image: redis:latest
        container_name: demo-03_broker
        environment:
          - REDIS_REPLICATION_MODE=master
        ports:
          - "16379:6379"
        volumes:
          - ./data/redis_db/data:/var/lib/redis
          - ./data/redis_db/conf:/usr/local/etc/redis/redis.conf
        command: redis-server --requirepass redis123

    backend:
        image: postgres:14.1
        container_name: demo-03_backend
        environment:
          - POSTGRES_USER=dbc
          - POSTGRES_PASSWORD=dbc
          - POSTGRES_DB=task_result
        ports:
          - "15432:5432"
        volumes:
          - ./data/pgdb:/var/lib/postgresql/data

    scheduler:
        build:
            context: .
            dockerfile: dockerfile.jobs
        container_name: demo-03_scheduler
        working_dir: /usr/src
        command: celery --app=jobs.tasks beat --schedule=email-schedule --loglevel=info --logfile=jobs/logs/scheduler.log
        volumes:
          - ./project/jobs:/usr/src/jobs
        environment:
          - CELERY_BROKER_URL=redis://:redis123@broker:6379/0
          - CELERY_RESULT_BACKEND=db+postgresql://dbc:dbc@backend:5432/task_result
          - WEB_SERVER_URL=http://web:8080
        depends_on:
          - broker
          - backend

    worker:
        build:
            context: .
            dockerfile: dockerfile.jobs
        container_name: demo-03_worker
        working_dir: /usr/src
        command: celery --app=jobs.tasks worker --loglevel=info --logfile=jobs/logs/worker.log
        volumes:
          - ./project/jobs:/usr/src/jobs
        environment:
          - CELERY_BROKER_URL=redis://:redis123@broker:6379/0
          - CELERY_RESULT_BACKEND=db+postgresql://dbc:dbc@backend:5432/task_result
          - WEB_SERVER_URL=http://web:8080
        depends_on:
          - broker
          - backend

    flower:
        build:
            context: .
            dockerfile: dockerfile.jobs
        container_name: demo-03_flower
        command: celery --app=jobs.tasks flower --port=5555
        ports:
          - "5555:5555"
        environment:
          - CELERY_BROKER_URL=redis://:redis123@broker:6379/0
          - CELERY_RESULT_BACKEND=db+postgresql://dbc:dbc@backend:5432/task_result
        depends_on:
          - broker
          - backend
          - worker
          - scheduler


    web:
        build:
            context: .
            dockerfile: dockerfile.web
        container_name: demo-03_web
        working_dir: /usr/src
        command: flask run --host=0.0.0.0 --port=8080
        environment:
          - FLASK_APP=project/web/app
        ports:
          - "8080:8080"
        depends_on:
          - broker
          - backend
          - worker
          - scheduler

